CREATE TABLE accounts_Details
(
         
		ID	BIGINT	IDENTITY(1,1),
		CUSTOMER_ID	  VARCHAR(20)	,
		ACCOUNT_NUMBER	VARCHAR(25)	,
		ACCOUNT_NAME	VARCHAR(200),	
		ACCOUNT_TYPE	VARCHAR(50),	
		BALANCE_DATE	DATE	,
		ACCOUNT_CURR	CHAR(3)	,
		ACCOUNT_BALANCE	DECIMAL(16,3),	
		LAST_MODIFIED_DATE	TIMESTAMP	

);		



 
 CREATE TABLE Account_Transaction_Details
 (
     	ID	BIGINT	IDENTITY(1,1),
		ACCOUNT_NUMBER	VARCHAR(25)	,
		ACCOUNT_NAME	VARCHAR(200),	
		VALUE_DATE	DATE	,
		ACCOUNT_CURR	CHAR(3)	,
		DEBIT_AMOUNT	DECIMAL(16,3),
		CREDIT_AMOUNT	DECIMAL(16,3),
		TRANSACTION_TYPE	VARCHAR(6),
		NARRATION	VARCHAR(500),
		LAST_MODIFIED_DATE	TIMESTAMP
		
   );
    